name: Docker test on remote machine

on:
  workflow_dispatch:

jobs:
  run-container:
    runs-on: self-hosted

    steps:
      - name: Pull image
        run: |
          docker pull ghcr.io/jsingh2344/glacier-melt:latest

      - name: Test container (safe)
        run: |
          docker run --rm ghcr.io/jsingh2344/glacier-melt:latest --help
